name: Comment on "In Progress" Issue

on:
  issues:

jobs:
  comment-on-inprogress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log Event Payload
        run: echo "${{ toJson(github.event) }}"
      
      - name: Check for "In Progress" status
        id: check_status
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Checking issue status...");
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            
            if (labels.includes('In Progress')) {
              console.log("Issue is in progress.");
              core.setOutput('status', 'in_progress');
            } else {
              console.log("Issue is not in progress.");
              core.setOutput('status', 'not_in_progress');
            }
      
      - name: Add comment if issue is "In Progress"
        if: steps.check_status.outputs.status == 'in_progress'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Adding comment to issue...");
            const issueNumber = context.issue.number;
            const commentBody = 'This issue is now In Progress.';
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
