name: Comment on "In Progress" Issue

on:
  issues:

jobs:
  comment-on-inprogress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for "In Progress" status
        id: check_status
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const status = issue.status
            
            if (status == 'In Progress') {
              core.setOutput('status', 'in_progress');
            } else {
              core.setOutput('status', 'not_in_progress');
            }
      
      - name: Add comment if issue is "In Progress"
        if: steps.check_status.outputs.status == 'not_in_progress'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const commentBody = 'This issue is now In Progress.';
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
