name: Auto Update In Progress Time

on:
  issues:


jobs:
  updateInProgressTime:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue status was changed to "In Progress"
        if: >
           github.event.changes
       
        run: |
        
          echo "In Progress Time: $timestamp"

