name: Comment on Status Update

on:
  push:
    branches:
      - main   # Change to your default branch if it's different
  workflow_dispatch:
    inputs:
      status:
        description: 'Custom status'
        required: false

jobs:
  comment-on-status-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for status change
        id: check_status
        run: |
          if [ -n "${{ github.event.inputs.status }}" ]; then
            echo "Status has been updated to ${{ github.event.inputs.status }}"
            echo "status=${{ github.event.inputs.status }}" >> $GITHUB_ENV
          else
            echo "Status not provided or not updated"
            echo "status=not_updated" >> $GITHUB_ENV
          fi
          
      - name: Add comment if status is updated to "In Progress"
        if: env.status == 'In Progress'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const commentBody = 'This issue is now In Progress.';
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
